name: csm_view
description: A package to improve view development for csm applications.
version: 6.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.3
  go_router: ^15.1.1
  device_info_plus: ^11.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0

flutter:
  assets: 
    - 'assets/'
    - 'assets/business/'