name: csm_view
description: A package to improve view development for csm applications.
version: 7.0.1

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^12.2.0
  go_router: ^17.0.0
  get_it: ^9.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^6.0.0
    

flutter:
  assets: 
    - 'assets/'
    - 'assets/business/'